[package]
name = "raytrace-rust"
version = "0.2.0"
authors = ["matt"]
edition = "2018"

[lib]
name = "libraytracer"
path = "src/ppm_raytracer_lib/lib.rs"

[[bin]]
name = "ppm-raytracer"
path = "src/ppm_raytracer/bin.rs"

[dependencies]
rand = "0.7.3"